# Generated by Django 3.2.5 on 2021-09-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_contract_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
