# Generated by Django 3.2.5 on 2021-09-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210903_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created', '-id')},
        ),
    ]
